// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_6825c8b132fbf8c6, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_6825c8b132fbf8c6, []int{1}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "v1.User")
	proto.RegisterType((*Users)(nil), "v1.Users")
}

func init() { proto.RegisterFile("api/proto/user.proto", fileDescriptor_6825c8b132fbf8c6) }

var fileDescriptor_6825c8b132fbf8c6 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x95, 0x34, 0x69, 0x93, 0x5b, 0xa9, 0xc3, 0x55, 0x85, 0xac, 0xf0, 0xa3, 0xaa, 0x0b,
	0x9d, 0x1c, 0xb5, 0x4c, 0x88, 0xa9, 0x48, 0x48, 0xcc, 0x41, 0x2c, 0x2c, 0xc8, 0xd4, 0x97, 0x12,
	0xa9, 0x8d, 0x23, 0xdb, 0x2d, 0x62, 0xe5, 0x15, 0x78, 0x2b, 0x56, 0x5e, 0x81, 0x07, 0x41, 0xb6,
	0x13, 0x26, 0xdf, 0x73, 0xbe, 0x7b, 0x24, 0xfb, 0x18, 0xa6, 0xa2, 0xad, 0xcb, 0x56, 0x2b, 0xab,
	0xca, 0x83, 0x21, 0xcd, 0xfd, 0x88, 0xf1, 0x71, 0x59, 0x9c, 0x6d, 0x95, 0xda, 0xee, 0xa8, 0x74,
	0x0b, 0xa2, 0x69, 0x94, 0x15, 0xb6, 0x56, 0x8d, 0x09, 0x1b, 0xc5, 0x69, 0x47, 0xbd, 0x7a, 0x39,
	0xbc, 0x96, 0xb4, 0x6f, 0xed, 0x47, 0x80, 0xf3, 0xef, 0x08, 0x92, 0x47, 0x43, 0x1a, 0x27, 0x10,
	0xd7, 0x92, 0x45, 0xb3, 0x68, 0x31, 0xa8, 0xe2, 0x5a, 0x22, 0x42, 0xd2, 0x88, 0x3d, 0xb1, 0x78,
	0x16, 0x2d, 0xf2, 0xca, 0xcf, 0x38, 0x85, 0x94, 0xf6, 0xa2, 0xde, 0xb1, 0x81, 0x37, 0x83, 0xc0,
	0x02, 0xb2, 0x56, 0x18, 0xf3, 0xae, 0xb4, 0x64, 0x89, 0x07, 0xff, 0xda, 0x25, 0xda, 0x37, 0xd5,
	0x10, 0x4b, 0x43, 0xc2, 0x0b, 0x64, 0x30, 0x12, 0x52, 0x6a, 0x32, 0x86, 0x0d, 0xbd, 0xdf, 0x4b,
	0x3c, 0x07, 0xd8, 0x68, 0x12, 0x96, 0xe4, 0xb3, 0xb0, 0x6c, 0xe4, 0x6f, 0x93, 0x77, 0xce, 0xda,
	0x3a, 0x7c, 0x68, 0x65, 0x8f, 0xb3, 0x80, 0x3b, 0x67, 0x6d, 0xe7, 0x97, 0x90, 0xba, 0xb7, 0x18,
	0xbc, 0x80, 0xd4, 0x55, 0x64, 0x58, 0x34, 0x1b, 0x2c, 0xc6, 0xab, 0x8c, 0x1f, 0x97, 0xdc, 0x91,
	0x2a, 0xd8, 0xab, 0x7b, 0x18, 0x3b, 0xf9, 0x40, 0xfa, 0x58, 0x6f, 0x08, 0xaf, 0x21, 0xa9, 0x48,
	0x48, 0x3c, 0xe1, 0xa1, 0x2a, 0xde, 0x57, 0xc5, 0xef, 0x5c, 0x55, 0x45, 0xde, 0xe7, 0xcd, 0x7c,
	0xf2, 0xf9, 0xf3, 0xfb, 0x15, 0x67, 0x38, 0xf4, 0x7f, 0x60, 0x6e, 0xf3, 0xa7, 0x11, 0xbf, 0x09,
	0xeb, 0x43, 0x7f, 0x5c, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x7e, 0xa2, 0xe1, 0xa8, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Read(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Users, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Read(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Users, error) {
	out := new(Users)
	err := c.cc.Invoke(ctx, "/v1.UserService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Read(context.Context, *empty.Empty) (*Users, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Read(ctx context.Context, req *empty.Empty) (*Users, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.UserService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Read(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _UserService_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/user.proto",
}
